### ISSUE TITLE
No failed job will show in http://localhost:3000/resque/failed anymore

### ISSUE THREAD

**Issue by amandameng** [julienXX/resque-slack#7]
Hey, Great Gem!
Well, after I used this gem, there will be no failed jobs show on http://localhost:3000/resque/failed here, right?
Is this meant to work like this?

Thank you

**Comment by julienXX** [comment]
Thanks and yes that's intended. If you want multiple failure backends, you can do:
```
Resque::Failure::Multiple.classes = [Resque::Failure::Redis, Resque::Failure::Slack]
Resque::Failure.backend = Resque::Failure::Multiple
```

**Comment by amandameng** [comment]
@julienXX Thanks Julien 👍
